version: "3.2"
# docker-compose build
# docker-compose up -d
# docker container run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer
# docker exec -it screenshotbackend /bin/bash
# docker run --name holdup --restart always -v "C:/Temp:/test" -v /var/run/docker.sock:/var/run/docker.sock:ro shaynesweeney/holdup

networks:
  screenshotting:

services:
  frontend:
    build: 
      context: .\ImageDisplayFrontend\
      dockerfile: Dockerfile    
    container_name: screenshotfrontend
    ports:
      - "82:80"
    networks:
      - screenshotting
    depends_on: 
      - "backend"  
  backend:
    build: 
      context: .\
      dockerfile: BackendDockerFile
    container_name: screenshotbackend    
    networks:
      - screenshotting 
   # ports:
   #   - "50658:80"  
    volumes:
      - type: bind
        source: C:/Screenshots
        target: /app/dump/
